l_simp_chinese:
 gbbf_value_as_base: "作为基数"
 gbbf_value_from_base: "基础值"
 gbbf_value_from_base_weekly: "基础每周进度"
 gbbf_value_from_base_monthly: "基础每月进度"
 gbbf_value_from_base_yearly: "基础每年进度"
 gbbf_value_from_institution_levels: "[concept_institution]$gbbf_investment_levels$的总数"
 gbbf_value_from_country_monopolies: "$gbbf_country_monopolies$的总数量"
 gbbf_value_from_citizenship_restrictiveness: "[ROOT.GetCountry.GetNameNoFlag]的[GetLawGroup('lawgroup_citizenship').GetName]法律的$gbbf_restrictiveness$"
 gbbf_value_from_aegean_sea_ownership: "[GetGeographicRegion('geographic_region_aegean_sea').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_balkan_highlands_ownership: "[GetGeographicRegion('geographic_region_balkan_highlands').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_anatolia_ownership: "[GetGeographicRegion('geographic_region_anatolia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_levant_ownership: "[GetGeographicRegion('geographic_region_levant').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_aegyptus_ownership: "[GetGeographicRegion('geographic_region_aegyptus').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_italia_ownership: "[GetGeographicRegion('geographic_region_italia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_arabia_ownership: "[GetGeographicRegion('geographic_region_arabia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_nile_river_ownership: "[GetGeographicRegion('geographic_region_arabia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_danubia_ownership: "[GetGeographicRegion('geographic_region_danubia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_rumelia_ownership: "[GetGeographicRegion('geographic_region_rumelia').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_controlling_anatolia: "$gbbf_controlling$[GetGeographicRegion('geographic_region_anatolia').GetName][concept_georegion]"
 gbbf_value_from_controlling_balkan_highlands: "$gbbf_controlling$[GetGeographicRegion('geographic_region_balkan_highlands').GetName][concept_georegion]"
 gbbf_value_from_controlling_aegean_sea: "$gbbf_controlling$[GetGeographicRegion('geographic_region_aegean_sea').GetName][concept_georegion]"
 gbbf_value_from_controlling_levant: "$gbbf_controlling$[GetGeographicRegion('geographic_region_levant').GetName][concept_georegion]"
 gbbf_value_from_controlling_nile_river: "$gbbf_controlling$[GetGeographicRegion('geographic_region_nile_river').GetName][concept_georegion]"
 gbbf_value_from_controlling_arabia: "$gbbf_controlling$[GetGeographicRegion('geographic_region_arabia').GetName][concept_georegion]"
 gbbf_value_from_controlling_danubia: "$gbbf_controlling$[GetGeographicRegion('geographic_region_danubia').GetName][concept_georegion]"
 gbbf_value_from_controlling_rumelia: "$gbbf_controlling$[GetGeographicRegion('geographic_region_rumelia').GetName][concept_georegion]"
 gbbf_value_from_armenian_highlands_ownership: "[GetGeographicRegion('geographic_region_armenian_highlands').GetName][concept_georegion]中$gbbf_fully_owned$的$gbbf_states$数量"
 gbbf_value_from_controlling_armenian_highlands: "$gbbf_controlling$[GetGeographicRegion('geographic_region_armenian_highlands').GetName][concept_georegion]"